### PR TITLE
Fix {je ba bo cu}

### PR DESCRIPTION
**Pull request by hackerg**
This lets you say things like "jebabo cu," "jebabo .i", etc.

### CODE REVIEW

**Comment by mezohe** [comment]
This makes spaces between cmavo important ({mo .ibabo mo} parses but {mo .i ba bo mo} fails), and it also allows previously undefined things like {tijebabobabota}. Is that your intention?

**Comment by mezohe** [comment]
I also see that {je.i} works exactly like {.ije}. Is the {je.i} here just a cosmetic change or is it supposed to be usable in subsentences too (like in camxes-beta)?

**Comment by hackerg** [comment]
When I tried to parse the sentence {.i ny. ze'a sanli ca lonu ny. viska lo badydi'u kei jebabo cu masno cadzu pu'o lonu ny. sanli ca'u lo midju be by.}, it did not parse correctly. By adding the option to consume a tag before the LE clause of a sumti, it now parses successfully.

**Comment by mezohe** [comment]
That in turn would disallow {ba lo broda je ba ko'a}. I'm testing a change that should fix {je ba bo cu} without breaking that and will post later today if all is well.

**Comment by mezohe** [comment]
See https://github.com/mezohe/ilmentufa/commit/e142ee

**Comment by hackerg** [comment]
From Menzohe:

This adds a negative predicate to the {TERM JA TERM} construction, analogous to
how {lo nu broda ba brode} is implemented, and adds term_2 and term_3 rules to
camxes-exp like those in camxes-beta for better readability.

Also, camxes_postproc.js gains a basic command-line interface (camxes output on
stdin, prettified output on stdout).

**Pull request merged**
